routes/web.php
<?php

use App\Http\Controllers\{CompanyController, EmployeeController, PositionController};
use Illuminate\Support\Facades\Route;

Route::view('/','dashboard');

Route::resources([
    'companies' => CompanyController::class,
    'positions' => PositionController::class,
    'employees' => EmployeeController::class
]);
Route::get('exportPDF',[EmployeeController::class,'exportPDF']);
Route::get('exportExcel',[EmployeeController::class,'exportExcel']);
Route::get('exportPDFcompany',[CompanyController::class,'exportPDF']);
Route::get('exportExcelcompany',[CompanyController::class,'exportExcel']);

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;
    protected $fillable = ['nama','alamat'];
}

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;

    protected $fillable = ['nama','position_id','company_id'];

    public function position()
    {
        return $this->belongsTo(Position::class);
    }

    public function company()
    {
        return $this->belongsTo(Company::class);
    }

}

app/Models/Position.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Position extends Model
{
    use HasFactory;
    protected $fillable = ['nama'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Models\Company;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\CompanyExport;

class CompanyController extends Controller
{
    public function index()
    {
        $companies = Company::get();
        return view('company.index',compact('companies'));
    }

    public function create()
    {
        return view('company.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'address' => 'required'
        ]);
        Company::create([
            'nama' => $request->name,
            'alamat' => $request->address
        ]);
        session()->flash('success','The company has been created successfully');
        return redirect()->route('companies.index');
    }

    public function edit($id)
    {
        return view('company.edit',[
            'company' => Company::find($id)
        ]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'address' => 'required'
        ]);
        $company = Company::findOrfail($id);
        $company->update([
            'nama' => $request->name,
            'alamat' => $request->address
        ]);
        session()->flash('success','The company has been updated successfully');
        return redirect()->route('companies.index');
    }

    public function exportExcel()
    {
        return Excel::download(new CompanyExport, 'Company.xlsx');
    }
    public function exportPDF()
    {       
        return Excel::download(new CompanyExport, 'Company.pdf');
    }

    public function destroy($id)
    {
        Company::find($id)->delete();
        return redirect()->route('companies.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Exports\EmployeeExport;
use App\Models\{Company,Employee,Position};
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;


class EmployeeController extends Controller
{
  
    public function index()
    {
        $employees = Employee::get();
        return view('employee.index',compact('employees'));
    }

    public function create()
    {
        return view('employee.create',[
            'positions' => Position::get(),
            'companies' => Company::get()
        ]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'company' => 'required',
            'position' => 'required'
        ]);
        Employee::create([
            'nama' => $request->name,
            'company_id' => $request->company,
            'position_id' => $request->position
        ]);
        session()->flash('success','The employee has been created successfully');
        return redirect()->route('employees.index');
    }

    public function edit($id)
    {
        return view('employee.edit',[
            'employee' => Employee::find($id),
            'companies' => Company::get(),
            'positions' => Position::get()
        ]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'company' => 'required',
            'position' => 'required'
        ]);
        $employee = Employee::findOrFail($id);
        $employee->update([
            'nama' => $request->name,
            'company_id' => $request->company,
            'position_id' => $request->position
        ]);
        session()->flash('success','The employee has been updated successfully');
        return redirect()->route('employees.index');
    }

    public function destroy($id)
    {
        Employee::find($id)->delete();
        return redirect()->route('employees.index');
    }

    public function exportExcel()
    {
        return Excel::download(new EmployeeExport, 'Employee.xlsx');
    }
    public function exportPDF()
    {       
        return Excel::download(new EmployeeExport, 'Employee.pdf');
    }
}

app/Http/Controllers/PositionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Position;
use Illuminate\Http\Request;

class PositionController extends Controller
{
    public function index()
    {
        $positions = Position::get();
        return view('position.index',compact('positions'));
    }

    public function create()
    {
        return view('position.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required'
        ]);
        Position::create([
            'nama' => $request->name
        ]);
        session()->flash('success','The position has been created successfully');
        return redirect()->route('positions.index');
    }

    public function edit($id)
    {
        return view('position.edit',[
            'position' => Position::find($id)
        ]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required'
        ]);
        $position = Position::findOrFail($id);
        $position->update([
            'nama' => $request->name
        ]);
        session()->flash('success','The position has been updated successfully');
        return redirect()->route('positions.index');
    }
    
    public function destroy($id)
    {
        Position::find($id)->delete();
        return redirect()->route('positions.index');
    }
}

resources/views/company/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row justify-content-center">
    <div class="card col-5 p-0">
        <div class="card-header">New Company</div>
        <div class="card-body">
            <form action="{{ route('companies.store') }}" method="post" autocomplete="off">
                @csrf
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" class="form-control">
                    @error('name')
                        <div class="text-danger mt-2">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                   <label for="address">Address</label>
                   <textarea name="address" id="address" rows="3" class="form-control"></textarea>
                    @error('address')
                        <div class="text-danger mt-2">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary ml-1" style="float:right"><i class="fas fa-save"></i> Save</button>
                    <a href="{{ route('companies.index') }}" class="btn btn-danger" style="float:right">Back</a>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/company/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row justify-content-center">
    <div class="card col-5 p-0">
        <div class="card-header">Edit Company</div>
        <div class="card-body">
            <form action="{{ route('companies.update',$company) }}" method="post" autocomplete="off">
                @method('put')
                @csrf
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" value="{{ $company->nama }}" class="form-control">
                    @error('name')
                        <div class="text-danger mt-2">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                   <label for="address">Address</label>
                   <textarea name="address" id="address" rows="3" class="form-control">{{ $company->alamat }}</textarea>
                    @error('address')
                        <div class="text-danger mt-2">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-warning ml-1" style="float:right">Update</button>
                    <a href="{{ route('companies.index') }}" class="btn btn-danger" style="float:right">Back</a>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/company/export.blade.php
<table>
    <thead>
        <tr>
            <th>No</th>
            <th>Nama</th>
            <th>alamat</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($data as $company)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $company->nama }}</td>
                <td>{{ $company->alamat }}</td>
            </tr>
        @endforeach
    </tbody>
</table>

resources/views/company/index.blade.php
@extends('layouts.app',['title'=> 'Companies'])

@section('content')
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <a href="{{ route('companies.create') }}" class="btn btn-primary btn-sm ml-5" style="float:right">Tambah</a>
        <a href="{{ url('exportExcelcompany') }}" class="btn btn-outline-success btn-sm ml-2" style="float:right">Excel</a>
        <a href="{{ url('exportPDFcompany') }}" class="btn btn-outline-danger btn-sm ml-1" style="float:right">PDF</a>
        <h5>Company</h5>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr> 
                        <th>No.</th>
                        <th>Nama</th>
                        <th>Alamat</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($companies as $company)    
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $company->nama }}</td>
                        <td>{{ $company->alamat }}</td>
                        <td>
                            <form action="{{ route('companies.destroy',$company) }}" method="post">
                                <a href="{{ route('companies.edit',$company) }}" class="btn btn-warning btn-sm" title="edit ?"><i class="fas fa-edit"></i></a>
                                @method('delete')
                                @csrf
                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('are you sure ?')" title="delete ?"><i class="fas fa-trash"></i></button>
                           </form>
                        </td>
                    </tr>
                   @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard.blade.php
@extends('layouts.app',['title' => 'Dashboard'])

@section('content')
   <div class="row">
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-secondary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-secondary text-uppercase mb-1">
                                Companies
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ DB::table('companies')->count() }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-file fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-secondary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-secondary text-uppercase mb-1">
                                Employees
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ DB::table('employees')->count() }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-file fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

         <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-secondary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-secondary text-uppercase mb-1">
                                Positions
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ DB::table('positions')->count() }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-file fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
   </div>
@endsection

resources/views/employee/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row justify-content-center">
    <div class="card col-5 p-0">
        <div class="card-header">New Employee</div>
        <div class="card-body">
            <form action="{{ route('employees.store') }}" method="post" autocomplete="off">
                @csrf
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" class="form-control">
                    @error('name')
                        <div class="text-danger mt-2">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="company">Company</label>
                    <select name="company" id="company" class="form-control">
                        <option disabled selected>Choose One!</option>
                        @foreach ($companies as $company)
                            <option value="{{ $company->id }}">{{ $company->nama }}</option>
                        @endforeach
                    </select>
                    @error('company')
                        <div class="text-danger mt-2">{{ $message }}</div>
                    @enderror
                </div>
                 <div class="form-group">
                    <label for="position">Position</label>
                    <select name="position" id="position" class="form-control">
                        <option disabled selected>Choose One!</option>
                        @foreach ($positions as $position)
                            <option value="{{ $position->id }}">{{ $position->nama }}</option>
                        @endforeach
                    </select>
                    @error('position')
                        <div class="text-danger mt-2">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary ml-1" style="float:right"><i class="fas fa-save"></i> Save</button>
                    <a href="{{ route('employees.index') }}" class="btn btn-danger" style="float:right">Back</a>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/employee/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row justify-content-center">
    <div class="card col-5 p-0">
        <div class="card-header">Edit Employee</div>
        <div class="card-body">
            <form action="{{ route('employees.update',$employee) }}" method="post" autocomplete="off">
                @method('put')
                @csrf
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" value="{{ $employee->nama }}" class="form-control">
                    @error('name')
                        <div class="text-danger mt-2">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="company">Company</label>
                    <select name="company" id="company" class="form-control">
                        @foreach ($companies as $company)
                            <option {{ $company->id == $employee->company_id ? 'selected' : '' }} value="{{ $company->id }}">{{ $company->nama }}</option>
                        @endforeach
                    </select>
                    @error('company')
                        <div class="text-danger mt-2">{{ $message }}</div>
                    @enderror
                </div>
                 <div class="form-group">
                    <label for="position">Position</label>
                    <select name="position" id="position" class="form-control">
                        @foreach ($positions as $position)
                            <option {{ $position->id == $employee->position_id ? 'selected' : '' }} value="{{ $position->id }}">{{ $position->nama }}</option>
                        @endforeach
                    </select>
                    @error('position')
                        <div class="text-danger mt-2">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-warning ml-1" style="float:right">Update</button>
                    <a href="{{ route('employees.index') }}" class="btn btn-danger" style="float:right">Back</a>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/employee/export.blade.php
<table>
    <thead>
        <tr>
            <th>No</th>
            <th>Nama</th>
            <th>Posisi</th>
            <th>Perusahaan</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($data as $employee)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $employee->nama }}</td>
                <td>{{ $employee->position->nama }}</td>
                <td>{{ $employee->company->nama }}</td>
            </tr>
        @endforeach
    </tbody>
</table>

resources/views/employee/index.blade.php
@extends('layouts.app',['title'=> 'Employees'])

@section('content')
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <a href="{{ route('employees.create') }}" class="btn btn-primary btn-sm ml-5" style="float:right">Tambah</a>
        <a href="{{ url('exportExcel') }}" class="btn btn-outline-success btn-sm ml-2" style="float:right">Excel</a>
        <a href="{{ url('exportPDF') }}" class="btn btn-outline-danger btn-sm ml-1" style="float:right">PDF</a>
        <h5>Employee</h5>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr> 
                        <th>No.</th>
                        <th>Nama</th>
                        <th>Posisi</th>
                        <th>Perusahaan</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($employees as $employee)    
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $employee->nama }}</td>
                        <td>{{ $employee->position->nama }}</td>
                        <td>{{ $employee->company->nama }}</td>
                        <td>
                            <form action="{{ route('employees.destroy',$employee) }}" method="post">
                                <a href="{{ route('employees.edit',$employee) }}" class="btn btn-warning btn-sm" title="edit ?"><i class="fas fa-edit"></i></a>
                                @method('delete')
                                @csrf
                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('are you sure ?')" title="delete ?"><i class="fas fa-trash"></i></button>
                           </form>
                        </td>
                    </tr>
                   @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/alert.blade.php
@if(Session::has('success'))
    <div class="alert alert-success">
        {{ Session::get('success') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <!-- CSRF Token -->
     <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ $title ?? config('app.name') }}</title>

    <link href="{{ asset('template/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <link href="{{ asset('template/css/sb-admin-2.min.css') }}" rel="stylesheet">
    <link href="{{ asset('template/vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
</head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        @include('layouts.sidebar')
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                
                @include('layouts.topbar')
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @include('layouts.alert')
                    @yield('content')
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; 2021 All rights reserved.</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    
    <!-- Bootstrap core JavaScript-->
    <script src="{{ asset('template/vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('template/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    
    <!-- Core plugin JavaScript-->
    <script src="{{ asset('template/vendor/jquery-easing/jquery.easing.min.js') }}"></script>
    
    <!-- Custom scripts for all pages-->
    <script src="{{ asset('template/js/sb-admin-2.min.js') }}"></script>
    
    <!-- Page level plugins -->
    <script src="{{ asset('template/vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('template/vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    
    <!-- Page level custom scripts -->
    <script src="{{ asset('template/js/demo/datatables-demo.js') }}"></script>
    
</body>
</html>

resources/views/layouts/sidebar.blade.php
<ul class="navbar-nav bg-gradient-dark sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-left justify-content-left" href="{{ url('/') }}">
        <div class="sidebar-brand-text mx-3">Company</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
        <a class="nav-link" href="{{ url('/') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Interface
    </div>

    <!-- Nav Item - Pages Collapse Menu -->

    <li class="nav-item">
        <a class="nav-link" href="{{ url('companies') }}">
            <i class="fas fa-fw fa-folder"></i>
            <span>Company</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{{ url('positions') }}">
            <i class="fas fa-fw fa-folder"></i>
            <span>Position</span>
        </a>
    </li>
     
    <li class="nav-item">
        <a class="nav-link" href="{{ url('employees') }}">
            <i class="fas fa-fw fa-folder"></i>
            <span>Employee</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>

resources/views/layouts/topbar.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Jhon Doe</span>
                <img class="img-profile rounded-circle"
                    src="{{ asset('template/img/undraw_profile.svg') }}">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    {{ __('Logout') }}
                </a>
            </div>
        </li>
    </ul>
</nav>

resources/views/position/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row justify-content-center">
    <div class="card col-5 p-0">
        <div class="card-header">New Position</div>
        <div class="card-body">
            <form action="{{ route('positions.store') }}" method="post" autocomplete="off">
                @csrf
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" class="form-control">
                    @error('name')
                        <div class="text-danger mt-2">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary ml-1" style="float:right"><i class="fas fa-save"></i> Save</button>
                    <a href="{{ route('positions.index') }}" class="btn btn-danger" style="float:right">Back</a>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/position/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row justify-content-center">
    <div class="card col-5 p-0">
        <div class="card-header">Edit Position</div>
        <div class="card-body">
            <form action="{{ route('positions.update',$position) }}" method="post" autocomplete="off">
                @method('put')
                @csrf
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" value="{{ $position->nama }}" class="form-control">
                    @error('name')
                        <div class="text-danger mt-2">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-warning ml-1" style="float:right">Update</button>
                    <a href="{{ route('positions.index') }}" class="btn btn-danger" style="float:right">Back</a>
            </form>
        </div>
    </div>
</div>
@endsection